Math-Magician: Components
Estherstarr/math-magician pull request #2
Opened 2022-05-25 19:47 UTC by Estherstarr

In this milestone, I implemented the following
- [ ] Delete all the boilerplate from CRA (text, images, styles).
- [ ] Create a directory called components.
- [ ] Create a new Calculator.js file Inside components.
- [ ] Styles in the App.css file

<img width="1174" alt="Screenshot 2022-05-25 at 7 46 42 PM" src="https://user-images.githubusercontent.com/60798978/170354925-770d201c-5493-4a41-90ec-09dddd835cd6.png">

2022-05-25 20:30 UTC, Wes-Isaac requested changes
Hi @Estherstarr, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Linters are set up properly ✔️.
- Readme looks professional 👀.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-05-25 20:30 UTC, Wes-Isaac commented on src/App.js
> -          {' '}
- [ ] Great job so far, to be consistent let's use class-based components. Kindly change this to a class-based component.

2022-05-25 20:30 UTC, Wes-Isaac commented on src/components/Calculator.js
> +            </div>
- [ ] Great job so far, it will be better to use buttons instead of `<b></b>` so that it will be semantically consistent.

2022-05-25 20:30 UTC, Wes-Isaac commented on src/components/Calculator.js
> +
- [ ] Kindly don't disable linters, if errors come up it's better to fix them. Kindly remove `eslint-disable`, line two.

2022-05-25 20:30 UTC, Wes-Isaac commented on public/index.html
>    </head>
- [ ] You have done a great job removing some of the boilerplate files, however, there're still some files that aren't removed kindly remove them.

![image](https://user-images.githubusercontent.com/59416136/170361682-6b467023-c0d9-4d47-b8da-f1a76514086e.png)

2022-05-25 20:59 UTC, Estherstarr commented
- [ ] Update App.js to class-based components

2022-05-26 09:32 UTC, thecodechaser approved these changes
## STATUS: APPROVED 🟢

## Hi @Estherstarr👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 09:34 UTC, merged