Math-Magicians: Events
Estherstarr/math-magician pull request #3
Opened 2022-05-26 19:33 UTC by Estherstarr

- [ ] Install big.js
- [ ] Add calculate.js and operate.js files into a logic directory
- [ ] Modify JSX tags in the Calculator.js file
- [ ] Add events to the calculator buttons of the Calculator.js file

2022-05-26 19:46 UTC, GzimAsani requested changes
### Hi @Estherstarr    
 
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job so far :clap: 
 
 ## Required Changes 
- [ ] Unfortunately, I cannot run your project, can you please take a step back and check it:

![image](https://user-images.githubusercontent.com/62705947/170565105-9c2e5162-31bd-4ad7-97f3-77391c5e1f0d.png)

- **Please fix it and request another CR**

 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 19:56 UTC, Estherstarr commented
It's compiling on my system. Please did you try installing the node modules with npm install
@GzimAsani

2022-05-26 20:03 UTC, GzimAsani commented
> It's compiling on my system. Please did you try installing the node modules with npm install
> @GzimAsani

Yes, I did try that, if you think the problem was on my side please ask for another CR

2022-05-26 21:21 UTC, Estherstarr commented
Hi, incase you run into issues installing the dependencies, you can delete the package-lock.json file and rerun the install commands  :slightly_smiling_face:

2022-05-26 21:57 UTC, Gambit142 requested changes
Hi @Estherstarr 👋, 

Good job so far!

## Highlights
- All linters checks passed 💯 
- Made use of the logic directory provided 💯 
- Use of state 💯 
- Use of lifecycle methods 💯 

However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-05-26 21:57 UTC, Gambit142 commented on src/components/Calculator.js
>              </div>
- [ ] You don't have an `onClick` function for **_3_**, so when I press 3, nothing is displayed. Kindly fix it. 👍

2022-05-26 21:57 UTC, Gambit142 commented on src/components/Calculator.js
> +              <button type="button" onClick={() => this.handleClick('%')}>%</button>
- [ ] One of the project requirements is that props need to be passed from the parent component (`Calculator`) to a child component. I would advise you to make the buttons you display a component and pass props from the Calculator component to the Button component. You are free to implement this requirement however you deem fit, but Kindly pass props from the Calculator component to the child component. 👍

2022-05-26 21:57 UTC, Gambit142 commented on src/components/Calculator.js
> +            <button type="button" className="calcSymbolsColor" onClick={() => this.handleClick('-')}>-</button>
- [ ] When I try to multiply two numbers, I get the error that `'×'` is not an operator. Based on the logic in the **_operate.js_** file the symbol for multiplication used is `'x'` and not `'×'`. Kindly make this change by passing the right string as a parameter for the `this.handleClick` function for multiplication. 👍

2022-05-27 09:00 UTC, Estherstarr commented
- [ ] Pass props from the Calculator component to the Button component

2022-05-27 09:12 UTC, Emmyn5600 approved these changes
Hi  @Estherstarr 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! :tada: :clap: :clap: :100:

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## Optional suggestions

- [ ] n/a

##### _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

##### Cheers and Happy coding!:clap::clap::clap:
##### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-27 09:45 UTC, merged